<img src="http://imgur.com/1ZcRyrc.png" style="float: left; margin: 20px; height: 55px">

# Capstone - Resumes and Job Ads Recommender

# Problem Statement

HR practitioners and/or hiring managers could have been spending too much time trying to sieve through many resumes for shortlisting suitable candidates whom they can contact for interview.
As a job seeker, we may also find ourselves spending so much times looking through plentiful job advertisements which may not be relevant to us.
Wouldn't it be nice if pre-selection can be done which will effectively save time for all of us?

We will be using Natural Language Processing (NLP) and Recommender System. Using cosine similarity, to identify similar job seekers / job advertisements.
Success will be evaluated based on the top recommendations and its features to see how closely matched are the jobs for the job seekers and vice versa.

# Executive Summary

We scrape the website jobspider.com for resumes. In view that api key is not available, we used BeautifulSoup and regex to get the desired information. As we encounter roadblock on the time connection timeout despite introducing bot agent, we limit the job categories to Accounting and Information Technology for this capstone. 
For the job ads, we based it on existing dataset that is available on Kaggle which was used for predicting fake job posting since the features in this dataset has 80% simiarity to the resumes dataset.

As we were cleaning the resumes dataset,we also decide which features will be important for us to have and which are the one to drop. In view that job title, objective, experience and skills are free texts that hold meaningful words for our analysis, we create a new feature and combine all where we then split the text into words, return them to their root form and also remove the stop words. These are performed for the job ads dataset as well.
We use TFidfVectorizer to calculate the weight of the words and not surprisely, words appear in resumes and often found in job ads.

For feature selection, we picked `location`, `education level`, `employment type`, `function`, `job level` as our initial criteria. We then put these features through cosine similarity metric, measuring the consine of the angle the features projected in a multi-dimension space to determine their similarity.

Noting that our dataset comprises of both job ads and resumes, we then need to slice the dataset together with the similarity scores that showcase resumes on the row index and job ads on the columns.

With that, we will be able to filter based on resumes returning top similarity scores for job ads and by tranposing the dataset, we then will also be able to get recommendated resumes based on similarity scores against job ads.


### Contents:
- [Pre-processing](#Pre-processing)
- [Data Dictionary](#Data-Dictionary)
- [Recommender System](#Recommender-System)
- [Conclusion](#Conclusion)
- [Limitation and Future Works](#Limitation-and-Future-Works)

In [1]:
import requests
import time
import pandas as pd
import numpy as np
import random
import matplotlib as plt
import seaborn as sns
import re
from scipy import sparse
from sklearn.metrics.pairwise import cosine_similarity, pairwise_distances
from IPython.display import HTML, display

%matplotlib inline

C:\Users\eukar\Anaconda3\lib\site-packages\statsmodels\tools\_testing.py:19: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
  import pandas.util.testing as tm


# Pre-processing

In [2]:
# Import resumes dataset
resumes = pd.read_csv('.\datasets\\resumes.csv')
resumes.head()

date_posted                                    job_title    industry state  \
0  2020-02-22                                      auditor  Accounting    TX   
1  2020-02-11                            senior accountant  Accounting    OH   
2  2020-01-31  senior/mid-level financial services manager  Accounting    TX   
3  2020-01-16                         brokerage operations  Accounting    NY   
4  2019-12-16                       full charge bookkeeper  Accounting    CO   

  state_name                  resume_href     id   emp_type availability  \
0      Texas  /job/view-resume-82470.html  82470   contract   02/22/2020   
1       Ohio  /job/view-resume-82450.html  82450  full-time     2/1/2020   
2      Texas  /job/view-resume-82423.html  82423  full-time          NaN   
3   New York  /job/view-resume-82397.html  82397  full-time    Immediate   
4   Colorado  /job/view-resume-82338.html  82338  full-time          NaN   

  desired_wage  ...   job_level will_travel    edu_level will_reloc  \
0          NaN  ...  mid_senior         Yes      masters        Yes   
1    75,000.00  ...  mid_senior          No  high_school         No   
2          NaN  ...  mid_senior         Yes    bachelors        Yes   
3        90000  ...  mid_senior          No  certificate         No   
4        35000  ...   associate          No    bachelors         No   

                                           objective  \
0  Strategist provides clients with more than a d...   
1                                                NaN   
2  Growth-focused and astute executive and influe...   
3  Analytical, performance-focused, and forward-t...   
4  Dynamic, goal-oriented, and analytical profess...   

                                                 exp  \
0  CPA Firm Consultant, Auditgoals.com 2019 - 202...   
1  Accomplished finance and accounting profession...   
2  WELLS FARGO ▪ DALLAS, TX (1994–2019)Senior Vic...   
3  SOCIÉTÉ GÉNÉRALE – JERSEY CITY, NJVice Preside...   
4  Echo River Expeditions, Cañon City, COReservat...   

                                                 edu  \
0  Master of Business Administration, FinanceBach...   
1       Three years at University Wisconsin Superior   
2  EDUCATIONApplied Business Administration Manag...   
3  SCS Business and Technical Institute -New York...   
4  Coursework in Accounting and ComputerBessemer ...   

                                              skills  \
0                                                NaN   
1  BudgetsAdvanced ExcelFinancial StatementsStaff...   
2  Banking Administration | Risk Mitigation |Staf...   
3  Trade Posting and Payment EscalationInvestment...   
4  Microsoft Office Applications (Excel, Word, Po...   

                                            add_info  \
0                                                NaN   
1  Software:Microsoft Dynamics GPPrism HRUltiproD...   
2                                                NaN   
3  EARLIER CAREERMAN FINANCIAL, INC. – NEW YORK, ...   
4                                                NaN   

                                        combine_text  
0  auditor strategist provides client decade hand...  
1  senior accountant accomplished finance account...  
2  senior mid level financial service manager gro...  
3  brokerage operation analytical performance foc...  
4  full charge bookkeeper dynamic goal oriented a...  

[5 rows x 21 columns]

In [3]:
# combine id and job_title as 1 for our index
resumes['index'] = 'R' + '_' + resumes['id'].astype(str) + '_' + resumes['job_title']

In [4]:
# Select features that we want to keep
res_df = resumes[['index', 'industry', 'state_name', 'emp_type', 'job_level', 'edu_level']]

# set id as the index
res_df = res_df.set_index('index')

res_df.head()

industry state_name  \
index                                                                       
R_82470_auditor                                     Accounting      Texas   
R_82450_senior accountant                           Accounting       Ohio   
R_82423_senior/mid-level financial services man...  Accounting      Texas   
R_82397_ brokerage operations                       Accounting   New York   
R_82338_full charge bookkeeper                      Accounting   Colorado   

                                                     emp_type   job_level  \
index                                                                       
R_82470_auditor                                      contract  mid_senior   
R_82450_senior accountant                           full-time  mid_senior   
R_82423_senior/mid-level financial services man...  full-time  mid_senior   
R_82397_ brokerage operations                       full-time  mid_senior   
R_82338_full charge bookkeeper                      full-time   associate   

                                                      edu_level  
index                                                            
R_82470_auditor                                         masters  
R_82450_senior accountant                           high_school  
R_82423_senior/mid-level financial services man...    bachelors  
R_82397_ brokerage operations                       certificate  
R_82338_full charge bookkeeper                        bachelors

As previously, we just assign number to the state names in accordance to alphabetical order, we get recommendations for location that could be far away from job seeker / job ads preference. Hence, we noq include 1 more feature name region.

In [5]:
# Listed out the states and it's region with reference from
# https://www.worldatlas.com/articles/the-regions-of-the-united-states.html

west = ['Alaska', 'Arizona', 'California', 'Colorado', 'Hawaii', 'Idaho', 'Montana', 'Nevada','New Mexico', 'Oregon',
       'Utah', 'Washington', 'Wyoming']

midwest = ['Illinois', 'Indiana', 'Iowa', 'Kansas', 'Michigan', 'Missouri', 'Minnesota', 'Nebraska', 'North Dakota', 
           'Ohio', 'South Dakota','Wisconsin']

south = ['Alabama', 'Arkansas', 'Delaware', 'Florida', 'Georgia', 'Kentucky', 'Louisiana', 'Maryland', 'Mississippi',
        'Oklahoma', 'North Carolina', 'South Carolina', 'Tennessee', 'Texas', 'Virginia', 'West Virginia', 'WashingtonDC']

northeast = ['Connecticut', 'Maine', 'New Hampshire', 'Massachusetts', 'New Jersey', 'New York', 'Pennsylvania',
            'Rhode Island', 'Vermont']

print('Number of states in the west region: ', len(west))
print('Number of states in the midwest region: ', len(midwest))
print('Number of states in the south region: ', len(south))
print('Number of states in the northeast region: ', len(northeast))

Number of states in the west region:  13
Number of states in the midwest region:  12
Number of states in the south region:  17
Number of states in the northeast region:  9


In [6]:
# To create 1 new feature 'region' for indicating the region of the states
region = []

for s in res_df['state_name']:
    if s in west:
        region.append('west')
    elif s in midwest:
        region.append('midwest')
    elif s in south:
        region.append('south')
    else:
        region.append('northeast')
        
res_df['region'] = region
res_df.head()

industry state_name  \
index                                                                       
R_82470_auditor                                     Accounting      Texas   
R_82450_senior accountant                           Accounting       Ohio   
R_82423_senior/mid-level financial services man...  Accounting      Texas   
R_82397_ brokerage operations                       Accounting   New York   
R_82338_full charge bookkeeper                      Accounting   Colorado   

                                                     emp_type   job_level  \
index                                                                       
R_82470_auditor                                      contract  mid_senior   
R_82450_senior accountant                           full-time  mid_senior   
R_82423_senior/mid-level financial services man...  full-time  mid_senior   
R_82397_ brokerage operations                       full-time  mid_senior   
R_82338_full charge bookkeeper                      full-time   associate   

                                                      edu_level     region  
index                                                                       
R_82470_auditor                                         masters      south  
R_82450_senior accountant                           high_school    midwest  
R_82423_senior/mid-level financial services man...    bachelors      south  
R_82397_ brokerage operations                       certificate  northeast  
R_82338_full charge bookkeeper                        bachelors       west

In [7]:
# Import job ads dataset
jobs = pd.read_csv('.\datasets\\job_ads.csv')
print(jobs.shape)
jobs.head()

(792, 19)


job_id                                              title state  \
0       9  ASP.net Developer Job opportunity at United St...    NJ   
1      10                   Applications Developer, Digital     CT   
2      38                          Technical Project Manager    NY   
3      49  Ruby Automation Engineer & Ruby on Rails Engin...    CA   
4      54               Mid-Senior .NET or Xamarin Developer    GA   

    state_name department   salary_range  \
0   New Jersey        NaN  100000-120000   
1  Connecticut        NaN            NaN   
2     New York        NaN            NaN   
3   California         IT            NaN   
4      Georgia        NaN         75-115   

                                     company_profile  \
0                                                NaN   
1  Novitex Enterprise Solutions, formerly Pitney ...   
2                                                NaN   
3                                                NaN   
4                                                NaN   

                                         description  \
0  DeveloperJob Location :United States-New Jerse...   
1  The Applications Developer, Digital will devel...   
2  GBI is a growing company developing several cu...   
3   # 1Ruby Automation Engineer Menlo Park, CA # ...   
4  DataFinch Technologies is the leader in electr...   

                                         requirement  \
0   #URL_86fd830a95a64e2b30ceed829e63fd384c289e4f...   
1  s:4 – 5 years’ experience in developing an...   
2  Must have excellent oral and written communica...   
3  Position # 1Ruby Automation EngineerLocation: ...   
4  We are looking for candidates who are generall...   

                                            benefits  telecommuting  \
0  Benefits - FullBonus Eligible - YesInterview T...              0   
1                                                NaN              0   
2  Experience with CRM, such as SugarCRM.Past emp...              0   
3                                                NaN              0   
4  Health, Vision, Dental, FSA, HSA, 401(k)Privat...              0   

   has_company_logo  has_questions employment_type required_experience  \
0                 0              0       full-time          mid_senior   
1                 1              0       full-time           associate   
2                 0              0       full-time           associate   
3                 0              1        contract          mid_senior   
4                 0              0       full-time          mid_senior   

  required_education                             industry  \
0          bachelors  Information Technology and Services   
1          bachelors                Management Consulting   
2          bachelors                   Financial Services   
3             degree                                  NaN   
4          bachelors                    Computer Software   

                 function                                       combine_text  
0  Information Technology  asp net developer job opportunity united state...  
1  Information Technology  application developer digital application deve...  
2  Information Technology  technical project manager gbi growing company ...  
3  Information Technology  ruby automation engineer ruby rail engineer 2 ...  
4  Information Technology  mid senior net xamarin developer datafinch tec...

In [8]:
# combine id and job_title as 1 for our index
jobs['index'] = 'J' + '_' + jobs['job_id'].astype(str) + '_' + jobs['title']

In [9]:
# Select features that we want to keep
jobs_df = jobs[['index', 'function', 'state_name', 'employment_type', 'required_experience', 'required_education']]

# set id as the index
jobs_df = jobs_df.set_index('index')
print(jobs_df.shape)
jobs_df.head()

(792, 5)


function  \
index                                                                        
J_9_ASP.net Developer Job opportunity at United...  Information Technology   
J_10_Applications Developer, Digital                Information Technology   
J_38_Technical Project Manager                      Information Technology   
J_49_Ruby Automation Engineer & Ruby on Rails E...  Information Technology   
J_54_Mid-Senior .NET or Xamarin Developer           Information Technology   

                                                     state_name  \
index                                                             
J_9_ASP.net Developer Job opportunity at United...   New Jersey   
J_10_Applications Developer, Digital                Connecticut   
J_38_Technical Project Manager                         New York   
J_49_Ruby Automation Engineer & Ruby on Rails E...   California   
J_54_Mid-Senior .NET or Xamarin Developer               Georgia   

                                                   employment_type  \
index                                                                
J_9_ASP.net Developer Job opportunity at United...       full-time   
J_10_Applications Developer, Digital                     full-time   
J_38_Technical Project Manager                           full-time   
J_49_Ruby Automation Engineer & Ruby on Rails E...        contract   
J_54_Mid-Senior .NET or Xamarin Developer                full-time   

                                                   required_experience  \
index                                                                    
J_9_ASP.net Developer Job opportunity at United...          mid_senior   
J_10_Applications Developer, Digital                         associate   
J_38_Technical Project Manager                               associate   
J_49_Ruby Automation Engineer & Ruby on Rails E...          mid_senior   
J_54_Mid-Senior .NET or Xamarin Developer                   mid_senior   

                                                   required_education  
index                                                                  
J_9_ASP.net Developer Job opportunity at United...          bachelors  
J_10_Applications Developer, Digital                        bachelors  
J_38_Technical Project Manager                              bachelors  
J_49_Ruby Automation Engineer & Ruby on Rails E...             degree  
J_54_Mid-Senior .NET or Xamarin Developer                   bachelors

In [10]:
# Check out the columns for each dataset
print(res_df.columns)
print('---------------------------------------------------------------------------------------')
print(jobs_df.columns)

Index(['industry', 'state_name', 'emp_type', 'job_level', 'edu_level',
       'region'],
      dtype='object')
---------------------------------------------------------------------------------------
Index(['function', 'state_name', 'employment_type', 'required_experience',
       'required_education'],
      dtype='object')


In [11]:
# Rename industry in res_df to function
res_df.rename(columns={'industry':'function'}, inplace=True)

# Rename employment_type, required_experience and required_education in jobs_df to the same as res_df
jobs_df.rename(columns={'employment_type':'emp_type', 'required_experience': 'job_level',
                       'required_education':'edu_level'}, inplace=True)

In [12]:
# Check the revised columns name
print(res_df.columns)
print('---------------------------------------------------------------------------------------')
print(jobs_df.columns)

Index(['function', 'state_name', 'emp_type', 'job_level', 'edu_level',
       'region'],
      dtype='object')
---------------------------------------------------------------------------------------
Index(['function', 'state_name', 'emp_type', 'job_level', 'edu_level'], dtype='object')


In [13]:
# To create 1 new feature 'region' for indicating the region of the states
region = []

for s in jobs_df['state_name']:
    if s in west:
        region.append('west')
    elif s in midwest:
        region.append('midwest')
    elif s in south:
        region.append('south')
    else:
        region.append('northeast')
        
jobs_df['region'] = region
jobs_df.head()

function  \
index                                                                        
J_9_ASP.net Developer Job opportunity at United...  Information Technology   
J_10_Applications Developer, Digital                Information Technology   
J_38_Technical Project Manager                      Information Technology   
J_49_Ruby Automation Engineer & Ruby on Rails E...  Information Technology   
J_54_Mid-Senior .NET or Xamarin Developer           Information Technology   

                                                     state_name   emp_type  \
index                                                                        
J_9_ASP.net Developer Job opportunity at United...   New Jersey  full-time   
J_10_Applications Developer, Digital                Connecticut  full-time   
J_38_Technical Project Manager                         New York  full-time   
J_49_Ruby Automation Engineer & Ruby on Rails E...   California   contract   
J_54_Mid-Senior .NET or Xamarin Developer               Georgia  full-time   

                                                     job_level  edu_level  \
index                                                                       
J_9_ASP.net Developer Job opportunity at United...  mid_senior  bachelors   
J_10_Applications Developer, Digital                 associate  bachelors   
J_38_Technical Project Manager                       associate  bachelors   
J_49_Ruby Automation Engineer & Ruby on Rails E...  mid_senior     degree   
J_54_Mid-Senior .NET or Xamarin Developer           mid_senior  bachelors   

                                                       region  
index                                                          
J_9_ASP.net Developer Job opportunity at United...  northeast  
J_10_Applications Developer, Digital                northeast  
J_38_Technical Project Manager                      northeast  
J_49_Ruby Automation Engineer & Ruby on Rails E...       west  
J_54_Mid-Senior .NET or Xamarin Developer               south

In [14]:
# Append both datasets together
combine = res_df.append(jobs_df, sort=False)

In [15]:
# Check to ensure we append correctly
print('res_df shape: ', res_df.shape)
print('job_df shape: ', jobs_df.shape)
print('combine shape: ', combine.shape)
combine.head()

res_df shape:  (1286, 6)
job_df shape:  (792, 6)
combine shape:  (2078, 6)


function state_name  \
index                                                                       
R_82470_auditor                                     Accounting      Texas   
R_82450_senior accountant                           Accounting       Ohio   
R_82423_senior/mid-level financial services man...  Accounting      Texas   
R_82397_ brokerage operations                       Accounting   New York   
R_82338_full charge bookkeeper                      Accounting   Colorado   

                                                     emp_type   job_level  \
index                                                                       
R_82470_auditor                                      contract  mid_senior   
R_82450_senior accountant                           full-time  mid_senior   
R_82423_senior/mid-level financial services man...  full-time  mid_senior   
R_82397_ brokerage operations                       full-time  mid_senior   
R_82338_full charge bookkeeper                      full-time   associate   

                                                      edu_level     region  
index                                                                       
R_82470_auditor                                         masters      south  
R_82450_senior accountant                           high_school    midwest  
R_82423_senior/mid-level financial services man...    bachelors      south  
R_82397_ brokerage operations                       certificate  northeast  
R_82338_full charge bookkeeper                        bachelors       west

Let's change all categorical features to nominal/ordinal.

In [16]:
# Change function to 1 is Accounting and 5 is Information Technology
combine['function'].replace(to_replace=['Accounting', 'Information Technology'], value=[1, 5], inplace=True)

In [17]:
# Change state_name to be represented by a number
# Check the number of state
print('There are {} unique states in state_name feature'. format(len(set(combine['state_name']))))
print('------------------------------------------------- ')
print(sorted(set(combine['state_name'])))

There are 49 unique states in state_name feature
------------------------------------------------- 
['Alabama', 'Alaska', 'Arizona', 'Arkansas', 'California', 'Colorado', 'Connecticut', 'Delaware', 'Florida', 'Georgia', 'Hawaii', 'Idaho', 'Illinois', 'Indiana', 'Iowa', 'Kansas', 'Kentucky', 'Louisiana', 'Maine', 'Maryland', 'Massachusetts', 'Michigan', 'Minnesota', 'Mississippi', 'Missouri', 'Montana', 'Nebraska', 'Nevada', 'New Hampshire', 'New Jersey', 'New Mexico', 'New York', 'North Carolina', 'Ohio', 'Oklahoma', 'Oregon', 'Pennsylvania', 'Rhode Island', 'South Carolina', 'South Dakota', 'Tennessee', 'Texas', 'Utah', 'Virginia', 'Washington', 'WashingtonDC', 'West Virginia', 'Wisconsin', 'Wyoming']


In [18]:
# Use pd.factorize to assign number to the state and create an nominal variable
combine['state_name'] = pd.factorize(combine['state_name'], sort=True)[0]

In [19]:
# Change emp_type to be represented by a number
# Check the number of emp_type
print('There are {} unique employment type in emp_type feature'. format(len(set(combine['emp_type']))))
print('-------------------------------------------------------- ')
print(set(combine['emp_type']))

There are 5 unique employment type in emp_type feature
-------------------------------------------------------- 
{'full-time', 'part-time', 'internship', 'other', 'contract'}


In [20]:
# Change emp_type to nominal
combine['emp_type'].replace(to_replace=['internship', 'part-time', 'contract', 'full-time', 'other'],
                           value=[1, 2, 3, 4, 5], inplace=True)

In [21]:
# Change job_level to be represented by a number
# Check the number of job_level
print('There are {} unique job level in job_level feature'. format(len(set(combine['job_level']))))
print('--------------------------------------------------- ')
print(set(combine['job_level']))

There are 5 unique job level in job_level feature
--------------------------------------------------- 
{'executive', 'mid_senior', 'internship', 'entry_level', 'associate'}


In [22]:
# Change job_level to ordinal where 1 is internship, 2 is entry_level..... 5 is executive
combine['job_level'].replace(to_replace=['internship', 'entry_level', 'associate', 'mid_senior', 'executive'],
                           value=[1, 2, 3, 4, 5], inplace=True)

In [23]:
# Change edu_level to be represented by a number
# Check the number of edu_level
print('There are {} unique education level in edu_level feature'. format(len(set(combine['edu_level']))))
print('--------------------------------------------------------')
print(set(combine['edu_level']))

There are 7 unique education level in edu_level feature
--------------------------------------------------------
{'college', 'masters', 'bachelors', 'certificate', 'high_school', 'unspecified', 'degree'}


In [24]:
# Change edu_level to ordinal where 1 is unspecified, 2 is high_school, 3 is college..... 7 is masters
combine['edu_level'].replace(to_replace=['unspecified', 'high_school', 'college', 'certificate',
                                        'degree', 'bachelors', 'masters'],
                           value=[1, 2, 3, 4, 5, 6, 7], inplace=True)

In [25]:
# Change region to ordinal where 1 is west, 2 is midwest, 3 is south and 4 is northeast
combine['region'].replace(to_replace=['west', 'midwest', 'south', 'northeast'],
                           value=[1, 2, 3, 4], inplace=True)

In [26]:
# Check out the final output for the changes
combine.head()

function  state_name  \
index                                                                      
R_82470_auditor                                            1          41   
R_82450_senior accountant                                  1          33   
R_82423_senior/mid-level financial services man...         1          41   
R_82397_ brokerage operations                              1          31   
R_82338_full charge bookkeeper                             1           5   

                                                    emp_type  job_level  \
index                                                                     
R_82470_auditor                                            3          4   
R_82450_senior accountant                                  4          4   
R_82423_senior/mid-level financial services man...         4          4   
R_82397_ brokerage operations                              4          4   
R_82338_full charge bookkeeper                             4          3   

                                                    edu_level  region  
index                                                                  
R_82470_auditor                                             7       3  
R_82450_senior accountant                                   2       2  
R_82423_senior/mid-level financial services man...          6       3  
R_82397_ brokerage operations                               4       4  
R_82338_full charge bookkeeper                              6       1

## Data Dictionary

In [27]:
%%html
<style>
table {float:left}
</style>

| Data Dictionary selected features 	|                                                                                                        	|
|:-----------------------------------	|:--------------------------------------------------------------------------------------------------------	|
| function                          	| Accounting = 1 and Information Technology = 5                                                          	|
| state_name                        	| Assigned number to each state in alphabetical order                                                    	|
| emp_type                          	| internship = 1, part-time = 2, contract = 3, full-time = 4, other = 5                                  	|
| job_level                         	| internship = 1, entry_level = 2, associate = 3, mid_senior = 4, executive = 5                          	|
| edu_level                         	| unspecified = 1, high_school = 2, college = 3, certificate = 4, degree = 5, bachelors = 6, masters = 7 	|
| region                            	| states by region where west = 1, midwest = 2, south = 3, northeast = 4                                 	|

In [28]:
# Get the mean centre of the matrix
def mean_centre(df):
    return(df.T - df.mean(axis=1)).T

combine_mc = mean_centre(combine)

In [29]:
# Get the similarity
sim_matrix = cosine_similarity(combine_mc)
combine_sim = pd.DataFrame(sim_matrix, columns=combine.index, index=combine.index)
combine_sim.head()

index                                               R_82470_auditor  \
index                                                                 
R_82470_auditor                                            1.000000   
R_82450_senior accountant                                  0.989553   
R_82423_senior/mid-level financial services man...         0.999157   
R_82397_ brokerage operations                              0.995230   
R_82338_full charge bookkeeper                             0.492707   

index                                               R_82450_senior accountant  \
index                                                                           
R_82470_auditor                                                      0.989553   
R_82450_senior accountant                                            1.000000   
R_82423_senior/mid-level financial services man...                   0.994157   
R_82397_ brokerage operations                                        0.996556   
R_82338_full charge bookkeeper                                       0.424512   

index                                               R_82423_senior/mid-level financial services manager  \
index                                                                                                     
R_82470_auditor                                                                              0.999157     
R_82450_senior accountant                                                                    0.994157     
R_82423_senior/mid-level financial services man...                                           1.000000     
R_82397_ brokerage operations                                                                0.997760     
R_82338_full charge bookkeeper                                                               0.481347     

index                                               R_82397_ brokerage operations  \
index                                                                               
R_82470_auditor                                                          0.995230   
R_82450_senior accountant                                                0.996556   
R_82423_senior/mid-level financial services man...                       0.997760   
R_82397_ brokerage operations                                            1.000000   
R_82338_full charge bookkeeper                                           0.444331   

index                                               R_82338_full charge bookkeeper  \
index                                                                                
R_82470_auditor                                                           0.492707   
R_82450_senior accountant                                                 0.424512   
R_82423_senior/mid-level financial services man...                        0.481347   
R_82397_ brokerage operations                                             0.444331   
R_82338_full charge bookkeeper                                            1.000000   

index                                               R_82293_remote bookkeeper or ranch management  \
index                                                                                               
R_82470_auditor                                                                          0.454494   
R_82450_senior accountant                                                                0.514949   
R_82423_senior/mid-level financial services man...                                       0.472953   
R_82397_ brokerage operations                                                            0.480659   
R_82338_full charge bookkeeper                                                           0.557370   

index                                               R_82266_financial analyst  \
index                                                                           
R_82470_auditor                                                      0.998301   
R_82450_senior accountant         

In [30]:
# Using for and if to filter index that is only resumes
for i in range(len(combine_sim.index)):
    if combine_sim.index[i][0] == 'R':
        index_res = combine_sim.iloc[:i]

# Check the shape and head of the filtered dataframe
print(index_res.shape)
index_res.head()

(1285, 2078)


index                                               R_82470_auditor  \
index                                                                 
R_82470_auditor                                            1.000000   
R_82450_senior accountant                                  0.989553   
R_82423_senior/mid-level financial services man...         0.999157   
R_82397_ brokerage operations                              0.995230   
R_82338_full charge bookkeeper                             0.492707   

index                                               R_82450_senior accountant  \
index                                                                           
R_82470_auditor                                                      0.989553   
R_82450_senior accountant                                            1.000000   
R_82423_senior/mid-level financial services man...                   0.994157   
R_82397_ brokerage operations                                        0.996556   
R_82338_full charge bookkeeper                                       0.424512   

index                                               R_82423_senior/mid-level financial services manager  \
index                                                                                                     
R_82470_auditor                                                                              0.999157     
R_82450_senior accountant                                                                    0.994157     
R_82423_senior/mid-level financial services man...                                           1.000000     
R_82397_ brokerage operations                                                                0.997760     
R_82338_full charge bookkeeper                                                               0.481347     

index                                               R_82397_ brokerage operations  \
index                                                                               
R_82470_auditor                                                          0.995230   
R_82450_senior accountant                                                0.996556   
R_82423_senior/mid-level financial services man...                       0.997760   
R_82397_ brokerage operations                                            1.000000   
R_82338_full charge bookkeeper                                           0.444331   

index                                               R_82338_full charge bookkeeper  \
index                                                                                
R_82470_auditor                                                           0.492707   
R_82450_senior accountant                                                 0.424512   
R_82423_senior/mid-level financial services man...                        0.481347   
R_82397_ brokerage operations                                             0.444331   
R_82338_full charge bookkeeper                                            1.000000   

index                                               R_82293_remote bookkeeper or ranch management  \
index                                                                                               
R_82470_auditor                                                                          0.454494   
R_82450_senior accountant                                                                0.514949   
R_82423_senior/mid-level financial services man...                                       0.472953   
R_82397_ brokerage operations                                                            0.480659   
R_82338_full charge bookkeeper                                                           0.557370   

index                                               R_82266_financial analyst  \
index                                                                           
R_82470_auditor                                                      0.998301   
R_82450_senior accountant         

In [31]:
# Now we need to further filter the column of index_res dataframe to list only the jobs
res_jobs = index_res.filter(regex='J_')

# Check the shape and head of the res_jobs dataframe
print(res_jobs.shape)
res_jobs.head()

(1285, 792)


index                                               J_9_ASP.net Developer Job opportunity at United States,New Jersey  \
index                                                                                                                   
R_82470_auditor                                                                              0.994142                   
R_82450_senior accountant                                                                    0.987669                   
R_82423_senior/mid-level financial services man...                                           0.994062                   
R_82397_ brokerage operations                                                                0.989066                   
R_82338_full charge bookkeeper                                                               0.432772                   

index                                               J_10_Applications Developer, Digital   \
index                                                                                       
R_82470_auditor                                                                  0.575739   
R_82450_senior accountant                                                        0.481228   
R_82423_senior/mid-level financial services man...                               0.555691   
R_82397_ brokerage operations                                                    0.510094   
R_82338_full charge bookkeeper                                                   0.533002   

index                                               J_38_Technical Project Manager  \
index                                                                                
R_82470_auditor                                                           0.992046   
R_82450_senior accountant                                                 0.984821   
R_82423_senior/mid-level financial services man...                        0.992179   
R_82397_ brokerage operations                                             0.987108   
R_82338_full charge bookkeeper                                            0.429062   

index                                               J_49_Ruby Automation Engineer & Ruby on Rails Engineer - 2 roles  \
index                                                                                                                  
R_82470_auditor                                                                              0.135198                  
R_82450_senior accountant                                                                    0.088784                  
R_82423_senior/mid-level financial services man...                                           0.118238                  
R_82397_ brokerage operations                                                                0.058617                  
R_82338_full charge bookkeeper                                                               0.428746                  

index                                               J_54_Mid-Senior .NET or Xamarin Developer  \
index                                                                                           
R_82470_auditor                                                                      0.900818   
R_82450_senior accountant                                                            0.858192   
R_82423_senior/mid-level financial services man...                                   0.890917   
R_82397_ brokerage operations                                                        0.858976   
R_82338_full charge bookkeeper                                                       0.619225   

index                                               J_103_Web Developer  \
index                                                                     
R_82470_auditor                                               -0.289073   
R_82450_senior accountant                                     -0.193178   
R_82423_senior/mid-level financial services man...            -0.265878   
R

In [32]:
# Saving a copy of the recommender system
res_jobs.to_csv('./datasets/res_jobs.csv', index=False)

## Recommender System

In [33]:
# Check the job recommendation for job seekers in Accounting function
print('Job seeker id {} is looking for {} job'.format(res_jobs.index[0][2:7], res_jobs.index[0][8:15]))
print('----------------------------------------------')
print('Top 10 job recommendations:')
res_jobs.iloc[0,:].sort_values(ascending=False)[0:10]

Job seeker id 82470 is looking for auditor job
----------------------------------------------
Top 10 job recommendations:


index
J_915_IT- Auditor                                            0.999812
J_6736_Senior Accountant                                     0.999472
J_4871_CPA Accounting Manager / Medical Billing              0.999157
J_701_Accountant / Book Keeper                               0.999058
J_4873_Controller - High Growth Specialty Finance Company    0.999058
J_10433_Payroll Accountant                                   0.998922
J_4193_Corporate Controller                                  0.998922
J_268_Sr. Accountant                                         0.998922
J_2128_Accounts Payable Supervisor                           0.998844
J_6081_Corporate Controller                                  0.998634
Name: R_82470_auditor, dtype: float64

In [34]:
# Using np.where to find the index number of the top 10 positions
print(np.where(jobs_df.index == "J_915_IT- Auditor"))
print(np.where(jobs_df.index == "J_6736_Senior Accountant"))
print(np.where(jobs_df.index == "J_4871_CPA Accounting Manager / Medical Billing"))
print(np.where(jobs_df.index == "J_701_Accountant / Book Keeper"))
print(np.where(jobs_df.index == "J_4873_Controller - High Growth Specialty Finance Company"))
print(np.where(jobs_df.index == "J_2128_Accounts Payable Supervisor"))
print(np.where(jobs_df.index == "J_687_Accountant"))
print(np.where(jobs_df.index == "J_3057_Accounting Manager"))
print(np.where(jobs_df.index == "J_6081_Corporate Controller "))
print(np.where(jobs_df.index == "J_10433_Payroll Accountant"))

(array([68], dtype=int64),)
(array([509], dtype=int64),)
(array([373], dtype=int64),)
(array([58], dtype=int64),)
(array([374], dtype=int64),)
(array([144], dtype=int64),)
(array([55], dtype=int64),)
(array([213], dtype=int64),)
(array([462], dtype=int64),)
(array([791], dtype=int64),)


In [35]:
# Creating the list of jobs into a dataframe
reco_acct = pd.DataFrame(jobs_df.iloc[[68, 509, 373, 58, 374, 144, 55, 213, 462, 791]])
reco_acct

function  \
index                                                            
J_915_IT- Auditor                                   Accounting   
J_6736_Senior Accountant                            Accounting   
J_4871_CPA Accounting Manager / Medical Billing     Accounting   
J_701_Accountant / Book Keeper                      Accounting   
J_4873_Controller - High Growth Specialty Finan...  Accounting   
J_2128_Accounts Payable Supervisor                  Accounting   
J_687_Accountant                                    Accounting   
J_3057_Accounting Manager                           Accounting   
J_6081_Corporate Controller                         Accounting   
J_10433_Payroll Accountant                          Accounting   

                                                        state_name   emp_type  \
index                                                                           
J_915_IT- Auditor                                   North Carolina   contract   
J_6736_Senior Accountant                                     Texas   contract   
J_4871_CPA Accounting Manager / Medical Billing              Texas  full-time   
J_701_Accountant / Book Keeper                            Virginia  full-time   
J_4873_Controller - High Growth Specialty Finan...        Virginia  full-time   
J_2128_Accounts Payable Supervisor                        Oklahoma  full-time   
J_687_Accountant                                          New York  full-time   
J_3057_Accounting Manager                                    Maine  full-time   
J_6081_Corporate Controller                               New York  full-time   
J_10433_Payroll Accountant                            Pennsylvania  full-time   

                                                     job_level  edu_level  \
index                                                                       
J_915_IT- Auditor                                   mid_senior  bachelors   
J_6736_Senior Accountant                             associate  bachelors   
J_4871_CPA Accounting Manager / Medical Billing     mid_senior  bachelors   
J_701_Accountant / Book Keeper                      mid_senior  bachelors   
J_4873_Controller - High Growth Specialty Finan...  mid_senior  bachelors   
J_2128_Accounts Payable Supervisor                   associate  bachelors   
J_687_Accountant                                    mid_senior  bachelors   
J_3057_Accounting Manager                           mid_senior  bachelors   
J_6081_Corporate Controller                         mid_senior  bachelors   
J_10433_Payroll Accountant                          mid_senior  bachelors   

                                                       region  
index                                                          
J_915_IT- Auditor                                       south  
J_6736_Senior Accountant                                south  
J_4871_CPA Accounting Manager / Medical Billing         south  
J_701_Accountant / Book Keeper                          south  
J_4873_Controller - High Growth Specialty Finan...      south  
J_2128_Accounts Payable Supervisor                      south  
J_687_Accountant                                    northeast  
J_3057_Accounting Manager                           northeast  
J_6081_Corporate Controller                         northeast  
J_10433_Payroll Accountant                          northeast

In [36]:
# Checking out the features of job seeker 82470
cdd_acct = res_df.head(1)
cdd_acct

function state_name  emp_type   job_level edu_level region
index                                                                        
R_82470_auditor  Accounting      Texas  contract  mid_senior   masters  south

In [37]:
# Putting both dataframe together where 1st row is the job seeker and remaining are recommendations
cdd_acct.append(reco_acct)

function  \
index                                                            
R_82470_auditor                                     Accounting   
J_915_IT- Auditor                                   Accounting   
J_6736_Senior Accountant                            Accounting   
J_4871_CPA Accounting Manager / Medical Billing     Accounting   
J_701_Accountant / Book Keeper                      Accounting   
J_4873_Controller - High Growth Specialty Finan...  Accounting   
J_2128_Accounts Payable Supervisor                  Accounting   
J_687_Accountant                                    Accounting   
J_3057_Accounting Manager                           Accounting   
J_6081_Corporate Controller                         Accounting   
J_10433_Payroll Accountant                          Accounting   

                                                        state_name   emp_type  \
index                                                                           
R_82470_auditor                                              Texas   contract   
J_915_IT- Auditor                                   North Carolina   contract   
J_6736_Senior Accountant                                     Texas   contract   
J_4871_CPA Accounting Manager / Medical Billing              Texas  full-time   
J_701_Accountant / Book Keeper                            Virginia  full-time   
J_4873_Controller - High Growth Specialty Finan...        Virginia  full-time   
J_2128_Accounts Payable Supervisor                        Oklahoma  full-time   
J_687_Accountant                                          New York  full-time   
J_3057_Accounting Manager                                    Maine  full-time   
J_6081_Corporate Controller                               New York  full-time   
J_10433_Payroll Accountant                            Pennsylvania  full-time   

                                                     job_level  edu_level  \
index                                                                       
R_82470_auditor                                     mid_senior    masters   
J_915_IT- Auditor                                   mid_senior  bachelors   
J_6736_Senior Accountant                             associate  bachelors   
J_4871_CPA Accounting Manager / Medical Billing     mid_senior  bachelors   
J_701_Accountant / Book Keeper                      mid_senior  bachelors   
J_4873_Controller - High Growth Specialty Finan...  mid_senior  bachelors   
J_2128_Accounts Payable Supervisor                   associate  bachelors   
J_687_Accountant                                    mid_senior  bachelors   
J_3057_Accounting Manager                           mid_senior  bachelors   
J_6081_Corporate Controller                         mid_senior  bachelors   
J_10433_Payroll Accountant                          mid_senior  bachelors   

                                                       region  
index                                                          
R_82470_auditor                                         south  
J_915_IT- Auditor                                       south  
J_6736_Senior Accountant                                south  
J_4871_CPA Accounting Manager / Medical Billing         south  
J_701_Accountant / Book Keeper                          south  
J_4873_Controller - High Growth Specialty Finan...      south  
J_2128_Accounts Payable Supervisor                      south  
J_687_Accountant                                    northeast  
J_3057_Accounting Manager                           northeast  
J_6081_Corporate Controller                         northeast  
J_10433_Payroll Accountant                          northeast

In [38]:
# Check the job recommendation for job seekers in Information Technology function
print('Job seeker id {} is looking for {} job'.format(res_jobs.index[1017][2:7], res_jobs.index[1017][8:45]))
print('---------------------------------------------------------------------')
print('Top 10 job recommendations:')
res_jobs.iloc[1017,:].sort_values(ascending=False)[0:10]

Job seeker id 75818 is looking for oracle database administrator job
---------------------------------------------------------------------
Top 10 job recommendations:


index
J_3500_IT Security Engineer, Immediate full time opening at Fortune 500 Co.    0.994085
J_2193_Sr. Java Developer                                                      0.994085
J_1478_IT Software Tester                                                      0.994085
J_3277_Oracle Applications DBA                                                 0.994085
J_8971_Java Integration Engineer                                               0.994085
J_6044_Lead Software Engineer                                                  0.994085
J_6523_Senior Software Engineer                                                0.994085
J_4945_Senior Systems Administrator                                            0.994085
J_2279_Web Developer                                                           0.994085
J_9842_Director, Information Security                                          0.994085
Name: R_75818_oracle database administrator, dtype: float64

In [39]:
# Using np.where to find the index number of the top 10 positions
print(np.where(jobs_df.index == "J_2433_Enterprise Architect"))
print(np.where(jobs_df.index == "J_1787_Software Engineer - IL"))
print(np.where(jobs_df.index == "J_1460_MOBILE FRONT END PROGRAMMERS - VLinks Media"))
print(np.where(jobs_df.index == "J_5653_Junior .NET Software Engineer"))
print(np.where(jobs_df.index == "J_4065_Senior Software Engineer - CloudSpotter Technologies"))
print(np.where(jobs_df.index == "J_666_Javascript Developer - Rippleshot"))
print(np.where(jobs_df.index == "J_6544_Linux System Manager - SaaS"))
print(np.where(jobs_df.index == "J_1677_SAP BI/HANA Managing Consultant"))
print(np.where(jobs_df.index == "J_496_Front-End Web Developer"))
print(np.where(jobs_df.index == "J_4498_Curam Developer"))

(array([165], dtype=int64),)
(array([117], dtype=int64),)
(array([100], dtype=int64),)
(array([440], dtype=int64),)
(array([293], dtype=int64),)
(array([53], dtype=int64),)
(array([491], dtype=int64),)
(array([111], dtype=int64),)
(array([29], dtype=int64),)
(array([333], dtype=int64),)


In [40]:
reco_it = pd.DataFrame(jobs_df.iloc[[165, 117, 100, 440, 293, 53, 491, 111, 29, 333]])
reco_it

function  \
index                                                                        
J_2433_Enterprise Architect                         Information Technology   
J_1787_Software Engineer - IL                       Information Technology   
J_1460_MOBILE FRONT END PROGRAMMERS - VLinks Media  Information Technology   
J_5653_Junior .NET Software Engineer                Information Technology   
J_4065_Senior Software Engineer - CloudSpotter ...  Information Technology   
J_666_Javascript Developer - Rippleshot             Information Technology   
J_6544_Linux System Manager - SaaS                  Information Technology   
J_1677_SAP BI/HANA Managing Consultant              Information Technology   
J_496_Front-End Web Developer                       Information Technology   
J_4498_Curam Developer                              Information Technology   

                                                   state_name   emp_type  \
index                                                                      
J_2433_Enterprise Architect                          Michigan   contract   
J_1787_Software Engineer - IL                        Illinois  full-time   
J_1460_MOBILE FRONT END PROGRAMMERS - VLinks Media   Illinois  full-time   
J_5653_Junior .NET Software Engineer                 Illinois  full-time   
J_4065_Senior Software Engineer - CloudSpotter ...   Illinois  full-time   
J_666_Javascript Developer - Rippleshot              Illinois  full-time   
J_6544_Linux System Manager - SaaS                   Illinois  full-time   
J_1677_SAP BI/HANA Managing Consultant               Illinois  full-time   
J_496_Front-End Web Developer                        Illinois  full-time   
J_4498_Curam Developer                               Illinois  full-time   

                                                     job_level  edu_level  \
index                                                                       
J_2433_Enterprise Architect                         mid_senior    masters   
J_1787_Software Engineer - IL                        associate  bachelors   
J_1460_MOBILE FRONT END PROGRAMMERS - VLinks Media   associate  bachelors   
J_5653_Junior .NET Software Engineer                 associate  bachelors   
J_4065_Senior Software Engineer - CloudSpotter ...  mid_senior  bachelors   
J_666_Javascript Developer - Rippleshot             mid_senior  bachelors   
J_6544_Linux System Manager - SaaS                  mid_senior  bachelors   
J_1677_SAP BI/HANA Managing Consultant              mid_senior  bachelors   
J_496_Front-End Web Developer                       mid_senior  bachelors   
J_4498_Curam Developer                              mid_senior  bachelors   

                                                     region  
index                                                        
J_2433_Enterprise Architect                         midwest  
J_1787_Software Engineer - IL                       midwest  
J_1460_MOBILE FRONT END PROGRAMMERS - VLinks Media  midwest  
J_5653_Junior .NET Software Engineer                midwest  
J_4065_Senior Software Engineer - CloudSpotter ...  midwest  
J_666_Javascript Developer - Rippleshot             midwest  
J_6544_Linux System Manager - SaaS                  midwest  
J_1677_SAP BI/HANA Managing Consultant              midwest  
J_496_Front-End Web Developer                       midwest  
J_4498_Curam Developer                              midwest

In [41]:
# Checking out the features of job seeker 75818
cdd_it = pd.DataFrame(res_df.iloc[1017]).T
cdd_it

function state_name  \
R_75818_oracle database administrator  Information Technology   Illinois   

                                       emp_type  job_level  edu_level   region  
R_75818_oracle database administrator  contract  associate  bachelors  midwest

In [42]:
# Putting both dataframe together where 1st row is the job seeker and remaining are recommendations
cdd_it.append(reco_it)

function  \
R_75818_oracle database administrator               Information Technology   
J_2433_Enterprise Architect                         Information Technology   
J_1787_Software Engineer - IL                       Information Technology   
J_1460_MOBILE FRONT END PROGRAMMERS - VLinks Media  Information Technology   
J_5653_Junior .NET Software Engineer                Information Technology   
J_4065_Senior Software Engineer - CloudSpotter ...  Information Technology   
J_666_Javascript Developer - Rippleshot             Information Technology   
J_6544_Linux System Manager - SaaS                  Information Technology   
J_1677_SAP BI/HANA Managing Consultant              Information Technology   
J_496_Front-End Web Developer                       Information Technology   
J_4498_Curam Developer                              Information Technology   

                                                   state_name   emp_type  \
R_75818_oracle database administrator                Illinois   contract   
J_2433_Enterprise Architect                          Michigan   contract   
J_1787_Software Engineer - IL                        Illinois  full-time   
J_1460_MOBILE FRONT END PROGRAMMERS - VLinks Media   Illinois  full-time   
J_5653_Junior .NET Software Engineer                 Illinois  full-time   
J_4065_Senior Software Engineer - CloudSpotter ...   Illinois  full-time   
J_666_Javascript Developer - Rippleshot              Illinois  full-time   
J_6544_Linux System Manager - SaaS                   Illinois  full-time   
J_1677_SAP BI/HANA Managing Consultant               Illinois  full-time   
J_496_Front-End Web Developer                        Illinois  full-time   
J_4498_Curam Developer                               Illinois  full-time   

                                                     job_level  edu_level  \
R_75818_oracle database administrator                associate  bachelors   
J_2433_Enterprise Architect                         mid_senior    masters   
J_1787_Software Engineer - IL                        associate  bachelors   
J_1460_MOBILE FRONT END PROGRAMMERS - VLinks Media   associate  bachelors   
J_5653_Junior .NET Software Engineer                 associate  bachelors   
J_4065_Senior Software Engineer - CloudSpotter ...  mid_senior  bachelors   
J_666_Javascript Developer - Rippleshot             mid_senior  bachelors   
J_6544_Linux System Manager - SaaS                  mid_senior  bachelors   
J_1677_SAP BI/HANA Managing Consultant              mid_senior  bachelors   
J_496_Front-End Web Developer                       mid_senior  bachelors   
J_4498_Curam Developer                              mid_senior  bachelors   

                                                     region  
R_75818_oracle database administrator               midwest  
J_2433_Enterprise Architect                         midwest  
J_1787_Software Engineer - IL                       midwest  
J_1460_MOBILE FRONT END PROGRAMMERS - VLinks Media  midwest  
J_5653_Junior .NET Software Engineer                midwest  
J_4065_Senior Software Engineer - CloudSpotter ...  midwest  
J_666_Javascript Developer - Rippleshot             midwest  
J_6544_Linux System Manager - SaaS                  midwest  
J_1677_SAP BI/HANA Managing Consultant              midwest  
J_496_Front-End Web Developer                       midwest  
J_4498_Curam Developer                              midwest

### Let's check out the candidates for HR/Hiring managers based on job ads

In [43]:
# Let's transpose the dataset
jobs_res = res_jobs.T
jobs_res.head()

index                                               R_82470_auditor  \
index                                                                 
J_9_ASP.net Developer Job opportunity at United...         0.994142   
J_10_Applications Developer, Digital                       0.575739   
J_38_Technical Project Manager                             0.992046   
J_49_Ruby Automation Engineer & Ruby on Rails E...         0.135198   
J_54_Mid-Senior .NET or Xamarin Developer                  0.900818   

index                                               R_82450_senior accountant  \
index                                                                           
J_9_ASP.net Developer Job opportunity at United...                   0.987669   
J_10_Applications Developer, Digital                                 0.481228   
J_38_Technical Project Manager                                       0.984821   
J_49_Ruby Automation Engineer & Ruby on Rails E...                   0.088784   
J_54_Mid-Senior .NET or Xamarin Developer                            0.858192   

index                                               R_82423_senior/mid-level financial services manager  \
index                                                                                                     
J_9_ASP.net Developer Job opportunity at United...                                           0.994062     
J_10_Applications Developer, Digital                                                         0.555691     
J_38_Technical Project Manager                                                               0.992179     
J_49_Ruby Automation Engineer & Ruby on Rails E...                                           0.118238     
J_54_Mid-Senior .NET or Xamarin Developer                                                    0.890917     

index                                               R_82397_ brokerage operations  \
index                                                                               
J_9_ASP.net Developer Job opportunity at United...                       0.989066   
J_10_Applications Developer, Digital                                     0.510094   
J_38_Technical Project Manager                                           0.987108   
J_49_Ruby Automation Engineer & Ruby on Rails E...                       0.058617   
J_54_Mid-Senior .NET or Xamarin Developer                                0.858976   

index                                               R_82338_full charge bookkeeper  \
index                                                                                
J_9_ASP.net Developer Job opportunity at United...                        0.432772   
J_10_Applications Developer, Digital                                      0.533002   
J_38_Technical Project Manager                                            0.429062   
J_49_Ruby Automation Engineer & Ruby on Rails E...                        0.428746   
J_54_Mid-Senior .NET or Xamarin Developer                                 0.619225   

index                                               R_82293_remote bookkeeper or ranch management  \
index                                                                                               
J_9_ASP.net Developer Job opportunity at United...                                       0.403224   
J_10_Applications Developer, Digital                                                    -0.182818   
J_38_Technical Project Manager                                                           0.385679   
J_49_Ruby Automation Engineer & Ruby on Rails E...                                       0.117647   
J_54_Mid-Senior .NET or Xamarin Developer                                                0.331539   

index                                               R_82266_financial analyst  \
index                                                                           
J_9_ASP.net Developer Job opportunity at United...                   0.988026   
J_10_Applications Developer, Digit

In [44]:
# Check the candidates for job ads in Accounting function
print('Job ad position: {} '.format(jobs_res.index[10][6:26]))
print('---------------------------------------')
print('Top 10 candidates recommendations:')
jobs_res.iloc[10,:].sort_values(ascending=False)[0:10]

Job ad position: Financial Accountant 
---------------------------------------
Top 10 candidates recommendations:


index
R_57471_staff accountant                      1.0
R_67483_data entry/accounting                 1.0
R_59270_invoicing specialist                  1.0
R_71690_bookkeeping/ office administrative    1.0
R_74990_senior staff accountant               1.0
R_75007_accounting assistant                  1.0
R_75465_bookkeeping, AR AP                    1.0
R_65285_senior accountant                     1.0
R_64594_accounts payable                      1.0
R_65175_accountant                            1.0
Name: J_187_Financial Accountant, dtype: float64

In [45]:
# Using np.where to find the index number of the top 10 job seekers
print(np.where(res_df.index == "R_75465_bookkeeping, AR AP"))
print(np.where(res_df.index == "R_67483_data entry/accounting"))
print(np.where(res_df.index == "R_59270_invoicing specialist"))
print(np.where(res_df.index == "R_65175_accountant"))
print(np.where(res_df.index == "R_65285_senior accountant"))
print(np.where(res_df.index == "R_57471_staff accountant"))
print(np.where(res_df.index == "R_74990_senior staff accountant"))
print(np.where(res_df.index == "R_75007_accounting assistant"))
print(np.where(res_df.index == "R_71690_bookkeeping/ office administrative"))
print(np.where(res_df.index == "R_68481_accountant"))

(array([136], dtype=int64),)
(array([265], dtype=int64),)
(array([433], dtype=int64),)
(array([320], dtype=int64),)
(array([317], dtype=int64),)
(array([462], dtype=int64),)
(array([152], dtype=int64),)
(array([151], dtype=int64),)
(array([206], dtype=int64),)
(array([246], dtype=int64),)


In [46]:
rec_acct = pd.DataFrame(res_df.iloc[[136,265, 433, 320, 317, 462, 152, 151, 206, 246]])
rec_acct

function state_name   emp_type  \
index                                                                          
R_75465_bookkeeping, AR AP                  Accounting   New York  full-time   
R_67483_data entry/accounting               Accounting   New York  full-time   
R_59270_invoicing specialist                Accounting   New York  full-time   
R_65175_accountant                          Accounting   New York  full-time   
R_65285_senior accountant                   Accounting   New York  full-time   
R_57471_staff accountant                    Accounting   New York  full-time   
R_74990_senior staff accountant             Accounting   New York  full-time   
R_75007_accounting assistant                Accounting   New York  full-time   
R_71690_bookkeeping/ office administrative  Accounting   New York  full-time   
R_68481_accountant                          Accounting   New York  full-time   

                                            job_level  edu_level     region  
index                                                                        
R_75465_bookkeeping, AR AP                  associate  bachelors  northeast  
R_67483_data entry/accounting               associate  bachelors  northeast  
R_59270_invoicing specialist                associate  bachelors  northeast  
R_65175_accountant                          associate  bachelors  northeast  
R_65285_senior accountant                   associate  bachelors  northeast  
R_57471_staff accountant                    associate  bachelors  northeast  
R_74990_senior staff accountant             associate  bachelors  northeast  
R_75007_accounting assistant                associate  bachelors  northeast  
R_71690_bookkeeping/ office administrative  associate  bachelors  northeast  
R_68481_accountant                          associate  bachelors  northeast

In [47]:
# Checking out the features of job ads 187
job_acct = pd.DataFrame(jobs_df.iloc[10]).T
job_acct

function state_name   emp_type  job_level  \
J_187_Financial Accountant  Accounting   New York  full-time  associate   

                            edu_level     region  
J_187_Financial Accountant  bachelors  northeast

In [48]:
# Putting both dataframe together where 1st row is the job ads and remaining are recommendations
job_acct.append(rec_acct)

function state_name   emp_type  \
J_187_Financial Accountant                  Accounting   New York  full-time   
R_75465_bookkeeping, AR AP                  Accounting   New York  full-time   
R_67483_data entry/accounting               Accounting   New York  full-time   
R_59270_invoicing specialist                Accounting   New York  full-time   
R_65175_accountant                          Accounting   New York  full-time   
R_65285_senior accountant                   Accounting   New York  full-time   
R_57471_staff accountant                    Accounting   New York  full-time   
R_74990_senior staff accountant             Accounting   New York  full-time   
R_75007_accounting assistant                Accounting   New York  full-time   
R_71690_bookkeeping/ office administrative  Accounting   New York  full-time   
R_68481_accountant                          Accounting   New York  full-time   

                                            job_level  edu_level     region  
J_187_Financial Accountant                  associate  bachelors  northeast  
R_75465_bookkeeping, AR AP                  associate  bachelors  northeast  
R_67483_data entry/accounting               associate  bachelors  northeast  
R_59270_invoicing specialist                associate  bachelors  northeast  
R_65175_accountant                          associate  bachelors  northeast  
R_65285_senior accountant                   associate  bachelors  northeast  
R_57471_staff accountant                    associate  bachelors  northeast  
R_74990_senior staff accountant             associate  bachelors  northeast  
R_75007_accounting assistant                associate  bachelors  northeast  
R_71690_bookkeeping/ office administrative  associate  bachelors  northeast  
R_68481_accountant                          associate  bachelors  northeast

In [49]:
# Check the candidates for job ads in Information Technology function
print('Job ad position: {} '.format(jobs_res.index[2][5:30]))
print('---------------------------------------')
print('Top 10 candidates recommendations:')
jobs_res.iloc[2,:].sort_values(ascending=False)[0:10]

Job ad position: Technical Project Manager 
---------------------------------------
Top 10 candidates recommendations:


index
R_78734_it service desk lead analyst\it service desk manager    1.000000
R_81761_sql server database administrator                       1.000000
R_79802_business system analyst                                 1.000000
R_72842_it support, it technician, systems administrator        1.000000
R_74072_windows systems engineer                                0.999971
R_74244_technical writer/editor                                 0.999971
R_81453_systems administrator                                   0.999971
R_75521_network engineer                                        0.999971
R_74692_business analyst / business systems analyst             0.999971
R_79968_system administrator                                    0.999971
Name: J_38_Technical Project Manager, dtype: float64

In [50]:
# Using np.where to find the index number of the top 10 job seekers
print(np.where(res_df.index == "R_72842_it support, it technician, systems administrator"))
print(np.where(res_df.index == "R_79802_business system analyst"))
print(np.where(res_df.index == "R_78734_it service desk lead analyst\it service desk manager"))
print(np.where(res_df.index == "R_81761_sql server database administrator"))
print(np.where(res_df.index == "R_74072_windows systems engineer"))
print(np.where(res_df.index == "R_74244_technical writer/editor"))
print(np.where(res_df.index == "R_75521_network engineer"))
print(np.where(res_df.index == "R_81453_systems administrator"))
print(np.where(res_df.index == "R_74692_business analyst / business systems analyst"))
print(np.where(res_df.index == "R_79968_system administrator"))

(array([1268], dtype=int64),)
(array([704], dtype=int64),)
(array([787], dtype=int64),)
(array([541], dtype=int64),)
(array([1183], dtype=int64),)
(array([1171], dtype=int64),)
(array([1069], dtype=int64),)
(array([563], dtype=int64),)
(array([1134], dtype=int64),)
(array([684], dtype=int64),)


In [51]:
rec_it = pd.DataFrame(res_df.iloc[[1268, 704, 787, 541, 1183, 1171, 1069, 563, 1134, 684]])
rec_it

function  \
index                                                                        
R_72842_it support, it technician, systems admi...  Information Technology   
R_79802_business system analyst                     Information Technology   
R_78734_it service desk lead analyst\it service...  Information Technology   
R_81761_sql server database administrator           Information Technology   
R_74072_windows systems engineer                    Information Technology   
R_74244_technical writer/editor                     Information Technology   
R_75521_network engineer                            Information Technology   
R_81453_systems administrator                       Information Technology   
R_74692_business analyst / business systems ana...  Information Technology   
R_79968_system administrator                        Information Technology   

                                                    state_name   emp_type  \
index                                                                       
R_72842_it support, it technician, systems admi...    New York  full-time   
R_79802_business system analyst                       New York  full-time   
R_78734_it service desk lead analyst\it service...    New York  full-time   
R_81761_sql server database administrator             New York  full-time   
R_74072_windows systems engineer                    New Jersey  full-time   
R_74244_technical writer/editor                     New Jersey  full-time   
R_75521_network engineer                            New Jersey  full-time   
R_81453_systems administrator                       New Jersey  full-time   
R_74692_business analyst / business systems ana...  New Jersey  full-time   
R_79968_system administrator                        New Jersey  full-time   

                                                    job_level  edu_level  \
index                                                                      
R_72842_it support, it technician, systems admi...  associate  bachelors   
R_79802_business system analyst                     associate  bachelors   
R_78734_it service desk lead analyst\it service...  associate  bachelors   
R_81761_sql server database administrator           associate  bachelors   
R_74072_windows systems engineer                    associate  bachelors   
R_74244_technical writer/editor                     associate  bachelors   
R_75521_network engineer                            associate  bachelors   
R_81453_systems administrator                       associate  bachelors   
R_74692_business analyst / business systems ana...  associate  bachelors   
R_79968_system administrator                        associate  bachelors   

                                                       region  
index                                                          
R_72842_it support, it technician, systems admi...  northeast  
R_79802_business system analyst                     northeast  
R_78734_it service desk lead analyst\it service...  northeast  
R_81761_sql server database administrator           northeast  
R_74072_windows systems engineer                    northeast  
R_74244_technical writer/editor                     northeast  
R_75521_network engineer                            northeast  
R_81453_systems administrator                       northeast  
R_74692_business analyst / business systems ana...  northeast  
R_79968_system administrator                        northeast

In [52]:
# Checking out the features of job seeker 38
job_it = pd.DataFrame(jobs_df.iloc[2]).T
job_it

function state_name   emp_type  \
J_38_Technical Project Manager  Information Technology   New York  full-time   

                                job_level  edu_level     region  
J_38_Technical Project Manager  associate  bachelors  northeast

In [53]:
# Putting both dataframe together where 1st row is the job ads and remaining are recommendations
job_it.append(rec_it)

function  \
J_38_Technical Project Manager                      Information Technology   
R_72842_it support, it technician, systems admi...  Information Technology   
R_79802_business system analyst                     Information Technology   
R_78734_it service desk lead analyst\it service...  Information Technology   
R_81761_sql server database administrator           Information Technology   
R_74072_windows systems engineer                    Information Technology   
R_74244_technical writer/editor                     Information Technology   
R_75521_network engineer                            Information Technology   
R_81453_systems administrator                       Information Technology   
R_74692_business analyst / business systems ana...  Information Technology   
R_79968_system administrator                        Information Technology   

                                                    state_name   emp_type  \
J_38_Technical Project Manager                        New York  full-time   
R_72842_it support, it technician, systems admi...    New York  full-time   
R_79802_business system analyst                       New York  full-time   
R_78734_it service desk lead analyst\it service...    New York  full-time   
R_81761_sql server database administrator             New York  full-time   
R_74072_windows systems engineer                    New Jersey  full-time   
R_74244_technical writer/editor                     New Jersey  full-time   
R_75521_network engineer                            New Jersey  full-time   
R_81453_systems administrator                       New Jersey  full-time   
R_74692_business analyst / business systems ana...  New Jersey  full-time   
R_79968_system administrator                        New Jersey  full-time   

                                                    job_level  edu_level  \
J_38_Technical Project Manager                      associate  bachelors   
R_72842_it support, it technician, systems admi...  associate  bachelors   
R_79802_business system analyst                     associate  bachelors   
R_78734_it service desk lead analyst\it service...  associate  bachelors   
R_81761_sql server database administrator           associate  bachelors   
R_74072_windows systems engineer                    associate  bachelors   
R_74244_technical writer/editor                     associate  bachelors   
R_75521_network engineer                            associate  bachelors   
R_81453_systems administrator                       associate  bachelors   
R_74692_business analyst / business systems ana...  associate  bachelors   
R_79968_system administrator                        associate  bachelors   

                                                       region  
J_38_Technical Project Manager                      northeast  
R_72842_it support, it technician, systems admi...  northeast  
R_79802_business system analyst                     northeast  
R_78734_it service desk lead analyst\it service...  northeast  
R_81761_sql server database administrator           northeast  
R_74072_windows systems engineer                    northeast  
R_74244_technical writer/editor                     northeast  
R_75521_network engineer                            northeast  
R_81453_systems administrator                       northeast  
R_74692_business analyst / business systems ana...  northeast  
R_79968_system administrator                        northeast

# Conclusion

Study shows that resumes screening remains the most time-consuming part of recruiting process where 52% of Talent Acquisition leaders cited that the hardest part of recruitment is screening candidates from a large applicant pool.
This process takes approximately 23 hours for just one hire and typically 75% to 88% of the resumes from the pool are unqualified.

Likewise for job seekers, we tend to send out tons of application only to hear nothing back in return. In addition, to ensure that the resume stands out, it is strongly recommended to tailor made the application materials to each job application. 

What we are trying achieve with the above model is to be able to take away the time-consuming part of the work for both recruitment process and job seekers.
This recommender system will return best-match profiles / job ads. So for the talent acquisition / job seekers, instead of looking through the large pool of information, they will be able to just focus on the recommendation which will already be matched based on their requirements.

With this recommendations, we plan to introduce a selection function (`Yes` or `No`). Talent acquisition leader / job seekers can have the option to choose `Yes` or `No` where yes to show interest and no refers to not interested.
When both job seeker and talent acquisition leader selected `Yes`, they will be connected to a chatroom to kickstart their conversation.

In [54]:
display(HTML("<table><tr><td><img src='images/app1.png'></td><td><img src='images/app2.png'></td><td><img src='images/app3.png'></td><td><img src='images/app4.png'></td></tr></table>"))

# Limitation and Future Works

**1. Unsupervised learning**\
The current metric is based on unsupervised learning. Upon successful implementation, as we go along, we will be able to collect more data on the success rate of matching or hire based on our recommendation. From there, we can ehance our metric to include supervised learning for better recommendation in the future.

**2. Adapt to local data**\
Currently, both dataset are US based data. Next, we need to explore to scrape local data, otherwise collect data through the app.

**3. Include all functions**\
To include more functions so that the app can cater to wider community.
FOCUS: General workers or student looking for part-time assignment to earn quick bucks. As there are many platforms to increase efficiency on recuitment for white collars / PMETs / Executive. This app aims to match quickly manpower that are needed urgently such as promoters, buffers, etc. Such roles typically don't require long interview process, thus the chat function allows employer to quickly connect to the job seeker for providing work information.

**4. Skill sets**\
As we observed earlier in EDA, job descriptions could consist of not only job description but experience, skills, compensation benefits, etc. The information we needed was the skill sets for better matching.
We need to further clean the data to capture the 'right' skill sets from multiple features.
Additionally, some function generally require more different skills and given the fast pace changing environment, need to take into consideration maintenance work for updating the set of skills.